image: python:3.9

codequality:
  stage: test
  script:
    - python -m pip install .[dev]
    - ./pre-commit

pages:
  stage: deploy
  only:
    - master
  script:
    - python -m pip install .[docs]
    - make -C docs/ html
    - mv ./docs/_build/html ./public
  artifacts:
    paths:
      - public/
