codequality:
  image: python:3.9
  stage: test
  script:
    - python -m pip install .[dev]
    - ./run-checks

pages:
  image: mono:slim
  stage: deploy
  only:
    - master
  before_script:
    - apt update
    - apt install -y python3
    - python3 --version
    - python --version
    - apt list | grep -P '^python3\.[0-9]
    - apt-get install python3.9 python3-pip
  script:
    - python -m pip install .[docs]
    - make -C docs/ html
    - mv ./docs/_build/html ./public
  artifacts:
    paths:
      - public/
